apiVersion: v1
kind: Service
metadata:
  name: trackme-app-service
spec:
  type: LoadBalancer
  selector:
    app: trackme-app
  ports:
    - protocol: TCP
      port: 80       # Внешний порт
      targetPort: 80 # Порт внутри контейнера